In [3]:
import numpy as np 

In [4]:
AdjacencyList= [[1,2],[3,4],[7,8],[],[5,6],[],[],[],[]]
print(AdjacencyList)

[[1, 2], [3, 4], [7, 8], [], [5, 6], [], [], [], []]


In [5]:
def admissable(index,markedList,AdjacencyList):
    for i in AdjacencyList[index]:
        if not markedList[i]:
            return True , i 
    return False,0

In [6]:
def DFS(startedNode,AdjacencyList):
    adjSize=len(AdjacencyList)
   
    markedNodes=np.zeros((adjSize),dtype=bool)
    pred=np.zeros((adjSize)) 
    order =np.zeros((adjSize))
    List =[]
    cntr=1
    pred[0]=-1
    order[startedNode]= cntr
    markedNodes[startedNode]=True 
    List.append(startedNode)
    while List:
    
        Size=len(List)
        index= List[Size-1]
        cureentNode , currentIndex = admissable(index,markedNodes,AdjacencyList)
        print(cureentNode)
     
        if cureentNode:
            pred[currentIndex]=index
            markedNodes[currentIndex]= True 
            cntr+=1
            order[currentIndex]=cntr
            List.append(currentIndex)
        else:
            anSize=len(List)
            
            List.pop(anSize-1)
    return pred,order,markedNodes       

In [7]:
DFS(0,AdjacencyList)
 

True
True
False
True
True
False
True
False
False
False
True
True
False
True
False
False
False


(array([-1.,  0.,  0.,  1.,  1.,  4.,  4.,  2.,  2.]),
 array([1., 2., 7., 3., 4., 5., 6., 8., 9.]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True]))